## **Title Name : 넘파이 문제풀이**

<p style="font-weight:bolder; font-size : 21px">
    Step : Day1
<p>
<p style="font-weight:bolder; font-size : 21px">
    Content : 커스텀 문제풀이
<p>
<p style="font-weight:bolder; font-size : 21px">
   RegDate : 2023.11.25
<p>

------------------------------------------------------------


<h2 style="font-weight:bolder; font-size : 25px">
문제풀이 : 
Q0 ~ Q10
<h2>

------------------------------------------------------

# 01. 환경설정
---------------------------------------------

In [156]:
# 시스템
import os
import sys
import random
from time import time

# 데이터분석 4종세트
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

# 시각화테마
sns.set_theme(style='whitegrid')
plt.style.use('dark_background')

# 유틸
import gc
import warnings
warnings.filterwarnings('ignore')

In [3]:
# 답안 초기화
Q0 = 0

# 02. 문제풀이
------------------------------------------

### 🔹 참고 사이트 링크
------------------------------------------
[참고사이트 : [Numpy] Numpy 문제 모음 정답 및 설명 (100 numpy exercises) - ing ](https://u-n-joe.tistory.com/94) 


In [6]:
#===============================================================
# Q11.  40 크기의 랜덤 벡터를 만들고 평균 값 찾기
#===============================================================

# 문제풀이 :
#---------------------------------------------------------------
Z = np.random.random(40)
Q11 = round(Z.mean(),3)

# 해답 :
#-----------------------------------------------------------------
Q11

0.558

In [23]:
#===============================================================
# Q12. 경계가 1이고 내부가 0 인 16x16 배열 만들기
#===============================================================

# 문제풀이 :
#---------------------------------------------------------------

Q12 = np.ones((16,16))
Q12[1:-1,1:-1] = 0

# 해답 :
#-----------------------------------------------------------------
Q12

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [18]:
#===============================================================
# Q13. 경계가 0이고 내부가 1인 5x5의 2차원 배열 만들기
#===============================================================

# 문제풀이 :
#---------------------------------------------------------------
Q13 = np.zeros((5,5))
Q13[1:-1,1:-1] = 1 


# 해답 :
#-----------------------------------------------------------------
Q13

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [57]:
#===============================================================
# Q14. 패딩을 이용하여 기존 어레이에 경계를 0으로만들기
#===============================================================

# 문제풀이 :
#---------------------------------------------------------------

arr = np.arange(30).reshape(3,10)
Q14 = np.pad(array=arr,pad_width=1)

# 해답 :
#-----------------------------------------------------------------
Q14

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9,  0],
       [ 0, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,  0],
       [ 0, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [65]:
#===============================================================
# Q15. 5x5 매트릭스 생성한뒤 대각선으로 1을 추가하기
#===============================================================
# 예시
'''
1, 0, 0, 0, 0
0, 1, 0, 0, 0
0, 0, 1, 0, 0
0, 0, 0, 1, 0
0, 0, 0, 0, 1
'''


# 문제풀이 :
#---------------------------------------------------------------
z = np.eye(5,dtype=int)
print(z)

# 해답 :
#-----------------------------------------------------------------
Q0

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


0

In [112]:
#===============================================================
# Q16. 8x8 매트릭스를 만들어 체크보드 패턴으로 채우기
#===============================================================

# 문제풀이 :
#---------------------------------------------------------------
Q16 = np.arange((64),dtype=int).reshape(8,8)
Q16[:]        = "0"
Q16[1::2,::2] = "1"
Q16[::2,1::2] = "1"



# 해답 :
#-----------------------------------------------------------------
Q16

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [153]:
#===============================================================
# Q17. 8x8 랜덤 행렬 정규화하기
#===============================================================

# 문제풀이 :
#---------------------------------------------------------------
np.random.seed(42)
arr = np.random.random(64).reshape(8,8)
mean = np.mean(arr)
std = np.std(arr)

Q17 = ((arr - mean) / std)


# 해답 :
#-----------------------------------------------------------------
Q17

array([[-0.31044753,  1.62167176,  0.88822371,  0.44110196, -1.04322864,
        -1.04330952, -1.37164001,  1.3381849 ],
       [ 0.44933958,  0.80800677, -1.49738804,  1.68604133,  1.22506433,
        -0.85436585, -0.95669074, -0.95139397],
       [-0.54618159,  0.1932818 , -0.11794825, -0.5898192 ,  0.48534757,
        -1.09864217, -0.58674917, -0.33787223],
       [-0.03704856,  1.06656215, -0.89683725,  0.15799777,  0.42016387,
        -1.41065032,  0.47090115, -0.99458654],
       [-1.34827387,  1.61553924,  1.67169626,  1.14443181, -0.54493573,
        -1.23888553,  0.72806418, -0.09042563],
       [-1.15717716,  0.09409102, -1.45109818,  1.48286311, -0.6986329 ,
         0.65526025, -0.5211359 ,  0.17755987],
       [ 0.26690095, -0.94653178,  1.68495073,  1.03288389,  1.58406261,
         1.4342627 ,  0.43855842,  1.52496063],
       [-1.26966807, -0.90921423, -1.41475189, -0.47546565, -0.26304051,
        -0.65648436,  1.21263969, -0.37009304]])

In [157]:
#===============================================================
# Q18. 색상을 4바이트(RGBA)로 나타내는 사용자 지정 dtype 생성
#===============================================================

# 문제풀이 :
#---------------------------------------------------------------
Q18 = np.dtype([
                    ("r", np.ubyte, 1),
                    ("g", np.ubyte, 1),
                    ("b", np.ubyte, 1),
                    ("a", np.ubyte, 1)
               ])

# 해답 :
#-----------------------------------------------------------------
Q18

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [191]:
#===============================================================
# Q19. 1차원 배열(1~20)의 5~17의 요소를 음수로 전환
#===============================================================
Q19 = np.arange(1,20+1).reshape(4,5)
Q19[(5 < Q19) & (Q19 < 17)] *= -1
# 해답 :
#-----------------------------------------------------------------
Q19

array([[  1,   2,   3,   4,   5],
       [ -6,  -7,  -8,  -9, -10],
       [-11, -12, -13, -14, -15],
       [-16,  17,  18,  19,  20]])

In [210]:
#===============================================================
# Q20. 어제, 오늘, 그리고 내일의 날짜를 알아보는법
#===============================================================

# 문제풀이 :
#---------------------------------------------------------------

today = np.datetime64('today')

Q20 =  \
f'''\
어제 : {today-1}
오늘 : {today} 
내일 : {today+1}
'''

# 해답 :
#-----------------------------------------------------------------
print(Q20)

어제 : 2023-11-25
오늘 : 2023-11-26 
내일 : 2023-11-27

