## **Title Name : 넘파이 문제풀이**

<p style="font-weight:bolder; font-size : 21px">
    Step : Day1
<p>
<p style="font-weight:bolder; font-size : 21px">
    Content : 커스텀 문제풀이
<p>
<p style="font-weight:bolder; font-size : 21px">
   RegDate : 2023.11.25
<p>

------------------------------------------------------------


<h2 style="font-weight:bolder; font-size : 25px">
문제풀이 : 
Q0 ~ Q10
<h2>

------------------------------------------------------

# 01. 환경설정
---------------------------------------------

In [2]:
# 시스템
import os
import sys
import random
from time import time

# 데이터분석 4종세트
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

# 시각화테마
sns.set_theme(style='whitegrid')
plt.style.use('dark_background')

In [3]:
# 답안 초기화
Q0 = 0

# 02. 문제풀이
------------------------------------------

### 🔹 참고 사이트 링크
------------------------------------------
[참고사이트 : [Numpy] Numpy 문제 모음 정답 및 설명 (100 numpy exercises) - ing ](https://u-n-joe.tistory.com/94) 


In [35]:
#===============================================================
# Q0. np이름으로 numpy 패키지 가져오기 
#===============================================================
import numpy as np

In [36]:
#===============================================================
# Q1.  numpy 버전 출력
#===============================================================

# 문제풀이 :
#---------------------------------------------------------------
Q1 = f'numpy_Ver : {np.__version__} 버전'

# 해답 :
#-----------------------------------------------------------------
Q1

'numpy_Ver : 1.25.2 버전'

In [37]:
#===============================================================
# Q2. 사이즈 10의 Null 벡터를 생성
#===============================================================

# 문제풀이 :
#---------------------------------------------------------------
Q2 = np.zeros(10)

# 해답 :
#-----------------------------------------------------------------
Q2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [38]:
#===============================================================
# Q3. 크기 10의 Null 벡터를 생성하고, 
#     두 번째 값인 555를 정수로 출력
#===============================================================

# 문제풀이 :
#---------------------------------------------------------------
Z = np.zeros(10)
Z2 = Z[1] = 555
Z2_int = int(Z[1])
Q3 = Z2_int

# 해답 :
#-----------------------------------------------------------------
Q3

555

In [39]:
#===============================================================
# Q4. 값이 10 ~ 49인 벡터를생성
#===============================================================

# 문제풀이 :
#---------------------------------------------------------------
Q6 = np.arange(10,49+1)

# 해답 :
#-----------------------------------------------------------------
Q6

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [40]:
#===============================================================
# Q5. 벡터를 반전하기
#===============================================================

# 문제풀이 :
#---------------------------------------------------------------
Q5 = Z[::-1]

# 해답 :
#-----------------------------------------------------------------
Q5

array([  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 555.,   0.])

In [41]:
#===============================================================
# Q6. 0~8 범위의 값을 사용하여 3x3 매트릭스 만들기
#===============================================================

# 문제풀이 :
#---------------------------------------------------------------
Q6 = np.arange(0,8+1).reshape(3,3)
# Q6 = np.arange(8+1).reshape(3,3)
# Q6 = np.arange(9).reshape(3,3)

# 해답 :
#-----------------------------------------------------------------
Q6

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [42]:
#===============================================================
# Q7. [1,2,0,0,4,0]에서 0이 아닌 요소의 인덱스를 출력
#===============================================================

# 문제풀이 :
#---------------------------------------------------------------
Q7 = np.nonzero([[1,2,0,0,4,0]])

# 해답 :
#-----------------------------------------------------------------
Q7 

(array([0, 0, 0], dtype=int64), array([0, 1, 4], dtype=int64))

In [43]:
#===============================================================
# Q8. 3x3 매트릭스 생성
#===============================================================

# 문제풀이 :
#---------------------------------------------------------------
Q8 = np.eye(3)

# 해답 :
#-----------------------------------------------------------------
Q8

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
#===============================================================
# Q9. 랜덤 값이 있는 3x3x3 어레이 생성
#===============================================================

# 문제풀이 :
#---------------------------------------------------------------
Q9 = np.random.random((3,3,3))

# 해답 :
#-----------------------------------------------------------------
Q9 

array([[[0.86654971, 0.77992593, 0.19111773],
        [0.47076232, 0.26142185, 0.53840002],
        [0.54317445, 0.3354884 , 0.63159555]],

       [[0.96418968, 0.66129263, 0.62288517],
        [0.23584881, 0.73166329, 0.8521859 ],
        [0.00737877, 0.99580984, 0.58465222]],

       [[0.09280007, 0.9151522 , 0.95937291],
        [0.62695443, 0.80478613, 0.19424588],
        [0.32038539, 0.68335472, 0.93411354]]])

In [45]:
#===============================================================
# Q10. 랜덤 값이 있는 10x10 배열을 만들고
#      최소값과 최대값을 찾기
#===============================================================

# 문제풀이 :
#---------------------------------------------------------------
rd10 = np.random.random(10)
rd10_min = rd10.min()
rd10_max = rd10.max()
rd10_min_round = round(rd10_min,2)
rd10_max_round = round(rd10_max,2)
Q10 = f' 최소값 : {rd10_min_round}.. , 최대값 : {rd10_max_round}..'

# 해답 :
#-----------------------------------------------------------------
Q10

' 최소값 : 0.12.. , 최대값 : 0.75..'

In [46]:
#===============================================================
# Q0.
#===============================================================

# 문제풀이 :
#---------------------------------------------------------------
# rd10 = np.random.random(10)
# rd10_min = rd10.min()
# rd10_max = rd10.max()
# rd10_min_round = round(rd10_min,2)
# rd10_max_round = round(rd10_max,2)
# Q10 = f' 최소값 : {rd10_min_round}... , 최대값 : {rd10_max_round}...'

# 해답 :
#-----------------------------------------------------------------
Q0

0