## **Title Name : 넘파이 문제풀이**

<p style="font-weight:bolder; font-size : 21px">
    Step : Day1
<p>
<p style="font-weight:bolder; font-size : 21px">
    Content : 커스텀 문제풀이 1번~10번
<p>
<p style="font-weight:bolder; font-size : 21px">
   RegDate : 2023.11.25
<p>

------------------------------------------------------------

# 01. 환경설정
---------------------------------------------

In [ ]:
# 시스템
import os
import sys
import random
from time import time

# 데이터분석 4종세트
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

# 시각화테마
sns.set_theme(style='whitegrid')
plt.style.use('dark_background')

# 02. 문제풀이
------------------------------------------

### Q1. ~ Q10.
------------------------------------------
[참고사이트 : [Numpy] Numpy 문제 모음 정답 및 설명 (100 numpy exercises) - ing ](https://u-n-joe.tistory.com/94) 

In [1]:
# 1. np이름으로 numpy 패키지 가져오기 
#-------------------------------------
import numpy as np

In [5]:
# 2.  numpy 버전 출력
#-------------------------------------
print(f'numpy_Ver : {np.__version__}버전')

numpy_Ver : 1.25.2버전


In [6]:
# 3. 사이즈 10의 Null 벡터를 생성
#-------------------------------------
Z = np.zeros(10)
Z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
# 4. 크기 10의 Null 벡터를 생성하고, 
#    두 번째 값인 555을 출력
#-------------------------------------
Z = np.zeros(10)
Z[1] = 555
print(int(Z[1]))

555


In [15]:
# 5. 값이 10 ~ 49인 벡터를생성
#-------------------------------------
Z = np.arange(10,49+1)
Z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [22]:
# 6. 벡터를 반전하기
#------------------------------------
Z[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [24]:
# 7. 0~8 범위의 값을 사용하여 3x3 매트릭스 만들기
#-------------------------------------
np.arange(0,8+1).reshape(3,3)
# np.arange(8+1).reshape(3,3)
# np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
# 8. [1,2,0,0,4,0]에서 0이 아닌 요소의 인덱스를 출력
#-------------------------------------
nz = np.nonzero([[1,2,0,0,4,0]])
nz

(array([0, 0, 0], dtype=int64), array([0, 1, 4], dtype=int64))

In [27]:
# 9. 3x3 매트릭스 생성
#-------------------------------------
Z = np.eye(3)
Z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
# 10. 랜덤 값이 있는 3x3x3 어레이 생성
#-------------------------------------
Z = np.random.random((3,3,3))
Z

array([[[0.04042131, 0.66668006, 0.12690814],
        [0.43236739, 0.78257997, 0.75932465],
        [0.69259607, 0.0216142 , 0.58182896]],

       [[0.07922313, 0.90104589, 0.68555846],
        [0.74789266, 0.4646186 , 0.60738994],
        [0.57634439, 0.91321239, 0.53508614]],

       [[0.807125  , 0.77896227, 0.93213329],
        [0.26755095, 0.70598851, 0.48913011],
        [0.72928193, 0.45020408, 0.93088087]]])

In [ ]:
#
#-------------------------------------